version: '3'
services:
  app:
    container_name: 'directory-app-api'
    volumes:
      - ./:/usr/src/app
    restart: always
    build: .
    ports:
      - '2255:2255'
    command: npm run dev
    links:
      - mongo
  mongo:
    container_name: 'mongo'
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
